# Generated by Django 3.0.8 on 2020-07-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='I', max_length=3)),
                ('stock_abbv', models.CharField(max_length=255, null=True)),
                ('stock_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='BullBearRatioSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='I', max_length=3)),
                ('trade_date', models.DateField(null=True)),
                ('scrape_datetime', models.DateTimeField(null=True)),
                ('bull_volume', models.IntegerField(null=True)),
                ('bear_volume', models.IntegerField(null=True)),
                ('close_price', models.FloatField(null=True)),
                ('bull_amount', models.FloatField(null=True)),
                ('bear_amount', models.FloatField(null=True)),
                ('bull_bear_ratio', models.FloatField(null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bull_bear_ratio', to='hkCbbcApi.StockSchema')),
            ],
            options={
                'db_table': 'bull_bear_ratios',
                'ordering': ('created_on',),
            },
        ),
    ]
