# Generated by Django 3.0.8 on 2020-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkCbbcApi', '0002_bullbearratioschema_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockschema',
            name='cbbc_abbv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
