# Generated by Django 3.0.8 on 2020-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkCbbcApi', '0003_stockschema_cbbc_abbv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockschema',
            old_name='stock_name',
            new_name='stock_name_en',
        ),
        migrations.AddField(
            model_name='stockschema',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockschema',
            name='stock_name_zh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
