# Generated by Django 3.0.8 on 2020-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkCbbcApi', '0004_auto_20200729_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bullbearratioschema',
            old_name='bear_amount',
            new_name='bear_chips_amount',
        ),
        migrations.RenameField(
            model_name='bullbearratioschema',
            old_name='bull_amount',
            new_name='bear_hedge_volume',
        ),
        migrations.RenameField(
            model_name='bullbearratioschema',
            old_name='bull_bear_ratio',
            new_name='bull_bear_ratio_for_chips',
        ),
        migrations.RenameField(
            model_name='bullbearratioschema',
            old_name='close_price',
            new_name='bull_bear_ratio_for_hedge_volume',
        ),
        migrations.RemoveField(
            model_name='bullbearratioschema',
            name='bear_volume',
        ),
        migrations.RemoveField(
            model_name='bullbearratioschema',
            name='bull_volume',
        ),
        migrations.AddField(
            model_name='bullbearratioschema',
            name='bull_chips_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bullbearratioschema',
            name='bull_hedge_volume',
            field=models.FloatField(null=True),
        ),
    ]
