# Generated by Django 3.0.8 on 2020-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkCbbcApi', '0007_auto_20200730_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullbearratioschema',
            name='bear_weighted_sum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bullbearratioschema',
            name='bull_weighted_sum',
            field=models.FloatField(null=True),
        ),
    ]
