# Generated by Django 3.0.8 on 2020-09-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkCbbcApi', '0008_auto_20200909_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bullbearratioschema',
            old_name='bear_weighted_sum',
            new_name='bear_weighted_average',
        ),
        migrations.RenameField(
            model_name='bullbearratioschema',
            old_name='bull_weighted_sum',
            new_name='bull_weighted_average',
        ),
    ]
